ASSET_IMAGE_PATHS = {
    "base": "bot/assets/images/farm/base/base.png",
    "farm_land_wet" : "bot/assets/images/farm/base/farmland_wet.png",
    "farm_land_dry" : "bot/assets/images/farm/base/farmland_dry.png",

    "crop_wheat_stage_1": "bot/assets/images/farm/crops/wheat/stage_1.png",
    "crop_wheat_stage_2": "bot/assets/images/farm/crops/wheat/stage_2.png",
    "crop_wheat_stage_3": "bot/assets/images/farm/crops/wheat/stage_3.png",
    "crop_wheat_stage_4": "bot/assets/images/farm/crops/wheat/stage_4.png",
    "item_wheat_seed": "bot/assets/images/farm/items/seeds/Wheat_seed.png",
    "item_wheat": "bot/assets/images/farm/items/crops/Wheat.png",

    "crop_corn_stage_1" : "bot/assets/images/farm/crops/corn/stage_1.png",
    "crop_corn_stage_2" : "bot/assets/images/farm/crops/corn/stage_2.png",
    "crop_corn_stage_3" : "bot/assets/images/farm/crops/corn/stage_3.png",
    "crop_corn_stage_4" : "bot/assets/images/farm/crops/corn/stage_4.png",
    "item_corn_seed" : "bot/assets/images/farm/items/seeds/Corn_seed.png",
    "item_corn" : "bot/assets/images/farm/items/crops/Corn.png",

    "crop_potato_stage_1" : "bot/assets/images/farm/crops/potato/stage_1.png",
    "crop_potato_stage_2" : "bot/assets/images/farm/crops/potato/stage_2.png",
    "crop_potato_stage_3" : "bot/assets/images/farm/crops/potato/stage_3.png",
    "crop_potato_stage_4" : "bot/assets/images/farm/crops/potato/stage_4.png",
    "item_potato_seed" : "bot/assets/images/farm/items/seeds/Potato_seed.png",
    "item_potato" : "bot/assets/images/farm/items/crops/Potato.png",

    "crop_parsnip_stage_1" : "bot/assets/images/farm/crops/parsnip/stage_1.png",
    "crop_parsnip_stage_2" : "bot/assets/images/farm/crops/parsnip/stage_2.png",
    "crop_parsnip_stage_3" : "bot/assets/images/farm/crops/parsnip/stage_3.png",
    "crop_parsnip_stage_4" : "bot/assets/images/farm/crops/parsnip/stage_4.png",
    "item_parsnip_seed" : "bot/assets/images/farm/items/seeds/Parsnip_seed.png",
    "item_parsnip" : "bot/assets/images/farm/items/crops/Parsnip.png",

    "crop_green_bean_stage_1" : "bot/assets/images/farm/crops/green_bean/stage_1.png",
    "crop_green_bean_stage_2" : "bot/assets/images/farm/crops/green_bean/stage_2.png",
    "crop_green_bean_stage_3" : "bot/assets/images/farm/crops/green_bean/stage_3.png",
    "crop_green_bean_stage_4" : "bot/assets/images/farm/crops/green_bean/stage_4.png",
    "item_green_bean_seed" : "bot/assets/images/farm/items/seeds/Green_Bean_seed.png",
    "item_green_bean" : "bot/assets/images/farm/items/crops/Green_Bean.png",

    "crop_hops_stage_1" : "bot/assets/images/farm/crops/hops/stage_1.png",
    "crop_hops_stage_2" : "bot/assets/images/farm/crops/hops/stage_2.png",
    "crop_hops_stage_3" : "bot/assets/images/farm/crops/hops/stage_3.png",
    "crop_hops_stage_4" : "bot/assets/images/farm/crops/hops/stage_4.png",
    "item_hops_seed" : "bot/assets/images/farm/items/seeds/Hops_seed.png",
    "item_hops" : "bot/assets/images/farm/items/crops/Hops.png",

    "crop_cauliflower_stage_1" : "bot/assets/images/farm/crops/cauliflower/stage_1.png",
    "crop_cauliflower_stage_2" : "bot/assets/images/farm/crops/cauliflower/stage_2.png",
    "crop_cauliflower_stage_3" : "bot/assets/images/farm/crops/cauliflower/stage_3.png",
    "crop_cauliflower_stage_4" : "bot/assets/images/farm/crops/cauliflower/stage_4.png",
    "item_cauliflower_seed" : "bot/assets/images/farm/items/seeds/Cauliflower_seed.png",
    "item_cauliflower" : "bot/assets/images/farm/items/crops/Cauliflower.png",

    "crop_garlic_stage_1" : "bot/assets/images/farm/crops/garlic/stage_1.png",
    "crop_garlic_stage_2" : "bot/assets/images/farm/crops/garlic/stage_2.png",
    "crop_garlic_stage_3" : "bot/assets/images/farm/crops/garlic/stage_3.png",
    "crop_garlic_stage_4" : "bot/assets/images/farm/crops/garlic/stage_4.png",
    "item_garlic_seed" : "bot/assets/images/farm/items/seeds/Garlic_seed.png",
    "item_garlic" : "bot/assets/images/farm/items/crops/Garlic.png",

    "crop_kale_stage_1" : "bot/assets/images/farm/crops/kale/stage_1.png",
    "crop_kale_stage_2" : "bot/assets/images/farm/crops/kale/stage_2.png",
    "crop_kale_stage_3" : "bot/assets/images/farm/crops/kale/stage_3.png",
    "crop_kale_stage_4" : "bot/assets/images/farm/crops/kale/stage_4.png",
    "item_kale_seed" : "bot/assets/images/farm/items/seeds/Kale_seed.png",
    "item_kale" : "bot/assets/images/farm/items/crops/Kale.png",

    "crop_rhubarb_stage_1" : "bot/assets/images/farm/crops/rhubarb/stage_1.png",
    "crop_rhubarb_stage_2" : "bot/assets/images/farm/crops/rhubarb/stage_2.png",
    "crop_rhubarb_stage_3" : "bot/assets/images/farm/crops/rhubarb/stage_3.png",
    "crop_rhubarb_stage_4" : "bot/assets/images/farm/crops/rhubarb/stage_4.png",
    "item_rhubarb_seed" : "bot/assets/images/farm/items/seeds/Rhubarb_seed.png",
    "item_rhubarb" : "bot/assets/images/farm/items/crops/Rhubarb.png",

    "crop_tomato_stage_1" : "bot/assets/images/farm/crops/tomato/stage_1.png",
    "crop_tomato_stage_2" : "bot/assets/images/farm/crops/tomato/stage_2.png",
    "crop_tomato_stage_3" : "bot/assets/images/farm/crops/tomato/stage_3.png",
    "crop_tomato_stage_4" : "bot/assets/images/farm/crops/tomato/stage_4.png",
    "item_tomato_seed" : "bot/assets/images/farm/items/seeds/Tomato_seed.png",
    "item_tomato" : "bot/assets/images/farm/items/crops/Tomato.png",

    "crop_melon_stage_1" : "bot/assets/images/farm/crops/melon/stage_1.png",
    "crop_melon_stage_2" : "bot/assets/images/farm/crops/melon/stage_2.png",
    "crop_melon_stage_3" : "bot/assets/images/farm/crops/melon/stage_3.png",
    "crop_melon_stage_4" : "bot/assets/images/farm/crops/melon/stage_4.png",
    "item_melon_seed" : "bot/assets/images/farm/items/seeds/Melon_seed.png",
    "item_melon" : "bot/assets/images/farm/items/crops/Melon.png",

    "crop_sugarcane_stage_1" : "bot/assets/images/farm/crops/sugarcane/sugarcane_1.png",
    "crop_sugarcane_stage_2" : "bot/assets/images/farm/crops/sugarcane/sugarcane_2.png",
    "crop_sugarcane_stage_3" : "bot/assets/images/farm/crops/sugarcane/sugarcane_3.png",
    "crop_sugarcane_stage_4" : "bot/assets/images/farm/crops/sugarcane/sugarcane_4.png",
    "item_sugarcane_seed" : "bot/assets/images/farm/items/seeds/sugarcane_seed.png",
    "item_sugarcane" : "bot/assets/images/farm/items/crops/sugarcane.png",

    "crop_sunflower_stage_1" : "bot/assets/images/farm/crops/sunflower/sunflower_1.png",
    "crop_sunflower_stage_2" : "bot/assets/images/farm/crops/sunflower/sunflower_2.png",
    "crop_sunflower_stage_3" : "bot/assets/images/farm/crops/sunflower/sunflower_3.png",
    "crop_sunflower_stage_4" : "bot/assets/images/farm/crops/sunflower/sunflower_4.png",
    "item_sunflower_seed" : "bot/assets/images/farm/items/seeds/sunflower_seed.png",
    "item_sunflower" : "bot/assets/images/farm/items/crops/sunflower.png",

    "chicken_1_image_key": "bot/assets/images/farm/animals/chicken/chicken_right.png",
    "chicken_2_image_key": "bot/assets/images/farm/animals/chicken/chicken_left.png",
    "cow_image_key" : "bot/assets/images/farm/animals/cow/cow_left.png",

    "item_chicken": "bot/assets/images/farm/animals/chicken/chicken_left.png",
    "item_cow": "bot/assets/images/farm/animals/cow/cow_left.png",

    "item_egg": "bot/assets/images/farm/items/animal_products/Egg.png",
    "item_milk": "bot/assets/images/farm/items/animal_products/Milk.png",

    "item_seaweed": "bot/assets/images/farm/seafood/Seaweed.png",
    "item_snail": "bot/assets/images/farm/seafood/Snail.png",
    "item_shrimp": "bot/assets/images/farm/seafood/Shrimp.png",
    "item_crab": "bot/assets/images/farm/seafood/Crab.png",
    "item_mussel": "bot/assets/images/farm/seafood/Mussel.png",
    "item_halibut": "bot/assets/images/farm/seafood/Halibut.png",
    "item_chub": "bot/assets/images/farm/seafood/Chub.png",
    "item_tilapia": "bot/assets/images/farm/seafood/Tilapia.png",
    "item_sturgeon": "bot/assets/images/farm/seafood/Sturgeon.png",
    "item_sea_cucumber": "bot/assets/images/farm/seafood/Sea_Cucumber.png",
    "item_squid": "bot/assets/images/farm/seafood/Squid.png",
    "item_red_snapper": "bot/assets/images/farm/seafood/Red_Snapper.png",
    "item_octopus": "bot/assets/images/farm/seafood/Octopus.png",
    "item_eel": "bot/assets/images/farm/seafood/Eel.png",
    "item_herring": "bot/assets/images/farm/seafood/Herring.png",
    "item_catfish": "bot/assets/images/farm/seafood/Catfish.png",
    "item_carp": "bot/assets/images/farm/seafood/Carp.png",
    "item_perch": "bot/assets/images/farm/seafood/Perch.png",
    "item_walleye": "bot/assets/images/farm/seafood/Walleye.png",
    "item_salmon": "bot/assets/images/farm/seafood/Salmon.png",
    "item_bream": "bot/assets/images/farm/seafood/Bream.png",
    "item_sardine": "bot/assets/images/farm/seafood/Sardine.png",
    "item_tuna": "bot/assets/images/farm/seafood/Tuna.png",
    "item_anchovy": "bot/assets/images/farm/seafood/Anchovy.png",
    "item_lobster": "bot/assets/images/farm/seafood/Lobster.png",
    "item_pufferfish": "bot/assets/images/farm/seafood/Pufferfish.png",

    "item_cheese": "bot/assets/images/farm/food/Cheese.png",
    "item_wheat_flour": "bot/assets/images/farm/food/Wheat_Flour.png",
    "item_oil": "bot/assets/images/farm/food/Oil.png",
    "item_sugar": "bot/assets/images/farm/food/Sugar.png",
    "item_fried_egg": "bot/assets/images/farm/food/Fried_Egg.png",
    "item_omelet": "bot/assets/images/farm/food/Omelet.png",
    "item_salad": "bot/assets/images/farm/food/Salad.png",
    "item_cheese_cauliflower": "bot/assets/images/farm/food/Cheese_Cauliflower.png",
    "item_parsnip_soup": "bot/assets/images/farm/food/Parsnip_Soup.png",
    "item_fried_calamari": "bot/assets/images/farm/food/Fried_Calamari.png",
    "item_pizza": "bot/assets/images/farm/food/Pizza.png",
    "item_bean_hotpot": "bot/assets/images/farm/food/Bean_Hotpot.png",
    "item_carp_surprise": "bot/assets/images/farm/food/Carp_Surprise.png",
    "item_hashbrowns": "bot/assets/images/farm/food/Hashbrowns.png",
    "item_pancakes": "bot/assets/images/farm/food/Pancakes.png",
    "item_salmon_dinner": "bot/assets/images/farm/food/Salmon_Dinner.png",
    "item_bread": "bot/assets/images/farm/food/Bread.png",
    "item_pink_cake": "bot/assets/images/farm/food/Pink_Cake.png",
    "item_rhubarb_pie": "bot/assets/images/farm/food/Rhubarb_Pie.png",
    "item_cookie": "bot/assets/images/farm/food/Cookie.png",
    "item_spaghetti": "bot/assets/images/farm/food/Spaghetti.png",
    "item_fried_eel": "bot/assets/images/farm/food/Fried_Eel.png",
    "item_sashimi": "bot/assets/images/farm/food/Sashimi.png",
    "item_maki_roll": "bot/assets/images/farm/food/Maki_Roll.png",
    "item_ice_cream": "bot/assets/images/farm/food/Ice_Cream.png",
    "item_crab_cakes": "bot/assets/images/farm/food/Crab_Cakes.png",
    "item_beer": "bot/assets/images/farm/food/Beer.png",

    "currency_chill_coin": "bot/assets/images/common/cs_coin.png",
    "level": "bot/assets/images/common/level.png",
    "exp": "bot/assets/images/common/xp.png",
    "shopScreen" : "bot/assets/images/farm/ui/shop.png",
    "train" : "bot/assets/images/farm/buildings/train.png",
    "item_bug": "bot/assets/images/farm/animals/bug.png",
}