ASSET_IMAGE_PATHS = {
    "base": "bot/assets/images/farm/base/base.png",
    "sakura": "bot/assets/images/farm/base/base_sakura.png",
    "snow": "bot/assets/images/farm/base/base_winter.png",
    "christmas": "bot/assets/images/farm/base/base_christmas.png",
    "halloween": "bot/assets/images/farm/base/base_halloween.png",
    "newYear": "bot/assets/images/farm/base/base_new_year.png",
    "cyberpunk": "bot/assets/images/farm/base/base_cyber.png",
    "farm_land_wet" : "bot/assets/images/farm/base/farmland_wet.png",
    "farm_land_dry" : "bot/assets/images/farm/base/farmland_dry.png",
    "hot_bar" : "bot/assets/images/farm/ui/hot_bar.png",

    "crop_wheat_stage_1": "bot/assets/images/farm/crops/wheat/stage_1.png",
    "crop_wheat_stage_2": "bot/assets/images/farm/crops/wheat/stage_2.png",
    "crop_wheat_stage_3": "bot/assets/images/farm/crops/wheat/stage_3.png",
    "crop_wheat_stage_4": "bot/assets/images/farm/crops/wheat/stage_4.png",
    "item_wheat_seed": "bot/assets/images/farm/items/seeds/Wheat_seed.png",
    "item_wheat": "bot/assets/images/farm/items/crops/Wheat.png",

    "crop_corn_stage_1" : "bot/assets/images/farm/crops/corn/stage_1.png",
    "crop_corn_stage_2" : "bot/assets/images/farm/crops/corn/stage_2.png",
    "crop_corn_stage_3" : "bot/assets/images/farm/crops/corn/stage_3.png",
    "crop_corn_stage_4" : "bot/assets/images/farm/crops/corn/stage_4.png",
    "item_corn_seed" : "bot/assets/images/farm/items/seeds/Corn_seed.png",
    "item_corn" : "bot/assets/images/farm/items/crops/Corn.png",

    "crop_potato_stage_1" : "bot/assets/images/farm/crops/potato/stage_1.png",
    "crop_potato_stage_2" : "bot/assets/images/farm/crops/potato/stage_2.png",
    "crop_potato_stage_3" : "bot/assets/images/farm/crops/potato/stage_3.png",
    "crop_potato_stage_4" : "bot/assets/images/farm/crops/potato/stage_4.png",
    "item_potato_seed" : "bot/assets/images/farm/items/seeds/Potato_seed.png",
    "item_potato" : "bot/assets/images/farm/items/crops/Potato.png",

    "crop_parsnip_stage_1" : "bot/assets/images/farm/crops/parsnip/stage_1.png",
    "crop_parsnip_stage_2" : "bot/assets/images/farm/crops/parsnip/stage_2.png",
    "crop_parsnip_stage_3" : "bot/assets/images/farm/crops/parsnip/stage_3.png",
    "crop_parsnip_stage_4" : "bot/assets/images/farm/crops/parsnip/stage_4.png",
    "item_parsnip_seed" : "bot/assets/images/farm/items/seeds/Parsnip_seed.png",
    "item_parsnip" : "bot/assets/images/farm/items/crops/Parsnip.png",

    "crop_green_bean_stage_1" : "bot/assets/images/farm/crops/green_bean/stage_1.png",
    "crop_green_bean_stage_2" : "bot/assets/images/farm/crops/green_bean/stage_2.png",
    "crop_green_bean_stage_3" : "bot/assets/images/farm/crops/green_bean/stage_3.png",
    "crop_green_bean_stage_4" : "bot/assets/images/farm/crops/green_bean/stage_4.png",
    "item_green_bean_seed" : "bot/assets/images/farm/items/seeds/Green_Bean_seed.png",
    "item_green_bean" : "bot/assets/images/farm/items/crops/Green_Bean.png",

    "crop_hops_stage_1" : "bot/assets/images/farm/crops/hops/stage_1.png",
    "crop_hops_stage_2" : "bot/assets/images/farm/crops/hops/stage_2.png",
    "crop_hops_stage_3" : "bot/assets/images/farm/crops/hops/stage_3.png",
    "crop_hops_stage_4" : "bot/assets/images/farm/crops/hops/stage_4.png",
    "item_hops_seed" : "bot/assets/images/farm/items/seeds/Hops_seed.png",
    "item_hops" : "bot/assets/images/farm/items/crops/Hops.png",

    "crop_cauliflower_stage_1" : "bot/assets/images/farm/crops/cauliflower/stage_1.png",
    "crop_cauliflower_stage_2" : "bot/assets/images/farm/crops/cauliflower/stage_2.png",
    "crop_cauliflower_stage_3" : "bot/assets/images/farm/crops/cauliflower/stage_3.png",
    "crop_cauliflower_stage_4" : "bot/assets/images/farm/crops/cauliflower/stage_4.png",
    "item_cauliflower_seed" : "bot/assets/images/farm/items/seeds/Cauliflower_seed.png",
    "item_cauliflower" : "bot/assets/images/farm/items/crops/Cauliflower.png",

    "crop_garlic_stage_1" : "bot/assets/images/farm/crops/garlic/stage_1.png",
    "crop_garlic_stage_2" : "bot/assets/images/farm/crops/garlic/stage_2.png",
    "crop_garlic_stage_3" : "bot/assets/images/farm/crops/garlic/stage_3.png",
    "crop_garlic_stage_4" : "bot/assets/images/farm/crops/garlic/stage_4.png",
    "item_garlic_seed" : "bot/assets/images/farm/items/seeds/Garlic_seed.png",
    "item_garlic" : "bot/assets/images/farm/items/crops/Garlic.png",

    "crop_kale_stage_1" : "bot/assets/images/farm/crops/kale/stage_1.png",
    "crop_kale_stage_2" : "bot/assets/images/farm/crops/kale/stage_2.png",
    "crop_kale_stage_3" : "bot/assets/images/farm/crops/kale/stage_3.png",
    "crop_kale_stage_4" : "bot/assets/images/farm/crops/kale/stage_4.png",
    "item_kale_seed" : "bot/assets/images/farm/items/seeds/Kale_seed.png",
    "item_kale" : "bot/assets/images/farm/items/crops/Kale.png",

    "crop_rhubarb_stage_1" : "bot/assets/images/farm/crops/rhubarb/stage_1.png",
    "crop_rhubarb_stage_2" : "bot/assets/images/farm/crops/rhubarb/stage_2.png",
    "crop_rhubarb_stage_3" : "bot/assets/images/farm/crops/rhubarb/stage_3.png",
    "crop_rhubarb_stage_4" : "bot/assets/images/farm/crops/rhubarb/stage_4.png",
    "item_rhubarb_seed" : "bot/assets/images/farm/items/seeds/Rhubarb_seed.png",
    "item_rhubarb" : "bot/assets/images/farm/items/crops/Rhubarb.png",

    "crop_tomato_stage_1" : "bot/assets/images/farm/crops/tomato/stage_1.png",
    "crop_tomato_stage_2" : "bot/assets/images/farm/crops/tomato/stage_2.png",
    "crop_tomato_stage_3" : "bot/assets/images/farm/crops/tomato/stage_3.png",
    "crop_tomato_stage_4" : "bot/assets/images/farm/crops/tomato/stage_4.png",
    "item_tomato_seed" : "bot/assets/images/farm/items/seeds/Tomato_seed.png",
    "item_tomato" : "bot/assets/images/farm/items/crops/Tomato.png",

    "crop_melon_stage_1" : "bot/assets/images/farm/crops/melon/stage_1.png",
    "crop_melon_stage_2" : "bot/assets/images/farm/crops/melon/stage_2.png",
    "crop_melon_stage_3" : "bot/assets/images/farm/crops/melon/stage_3.png",
    "crop_melon_stage_4" : "bot/assets/images/farm/crops/melon/stage_4.png",
    "item_melon_seed" : "bot/assets/images/farm/items/seeds/Melon_seed.png",
    "item_melon" : "bot/assets/images/farm/items/crops/Melon.png",

    "crop_sugarcane_stage_1" : "bot/assets/images/farm/crops/sugarcane/sugarcane_1.png",
    "crop_sugarcane_stage_2" : "bot/assets/images/farm/crops/sugarcane/sugarcane_2.png",
    "crop_sugarcane_stage_3" : "bot/assets/images/farm/crops/sugarcane/sugarcane_3.png",
    "crop_sugarcane_stage_4" : "bot/assets/images/farm/crops/sugarcane/sugarcane_4.png",
    "item_sugarcane_seed" : "bot/assets/images/farm/items/seeds/sugarcane_seed.png",
    "item_sugarcane" : "bot/assets/images/farm/items/crops/sugarcane.png",

    "crop_hot_pepper_stage_1" : "bot/assets/images/farm/crops/hot_pepper/Hot_Pepper_1.png",
    "crop_hot_pepper_stage_2" : "bot/assets/images/farm/crops/hot_pepper/Hot_Pepper_2.png",
    "crop_hot_pepper_stage_3" : "bot/assets/images/farm/crops/hot_pepper/Hot_Pepper_3.png",
    "crop_hot_pepper_stage_4" : "bot/assets/images/farm/crops/hot_pepper/Hot_Pepper_4.png",
    "item_hot_pepper_seed" : "bot/assets/images/farm/items/seeds/Hot_Pepper_seed.png",
    "item_hot_pepper" : "bot/assets/images/farm/items/crops/Hot_Pepper.png",

    "crop_red_cabbage_stage_1" : "bot/assets/images/farm/crops/red_cabbage/Red_Cabbage_1.png",
    "crop_red_cabbage_stage_2" : "bot/assets/images/farm/crops/red_cabbage/Red_Cabbage_2.png",
    "crop_red_cabbage_stage_3" : "bot/assets/images/farm/crops/red_cabbage/Red_Cabbage_3.png",
    "crop_red_cabbage_stage_4" : "bot/assets/images/farm/crops/red_cabbage/Red_Cabbage_4.png",
    "item_red_cabbage_seed" : "bot/assets/images/farm/items/seeds/Red_Cabbage_seed.png",
    "item_red_cabbage" : "bot/assets/images/farm/items/crops/Red_Cabbage.png",

    "crop_yam_stage_1" : "bot/assets/images/farm/crops/yam/Yam_1.png",
    "crop_yam_stage_2" : "bot/assets/images/farm/crops/yam/Yam_2.png",
    "crop_yam_stage_3" : "bot/assets/images/farm/crops/yam/Yam_3.png",
    "crop_yam_stage_4" : "bot/assets/images/farm/crops/yam/Yam_4.png",
    "item_yam_seed" : "bot/assets/images/farm/items/seeds/Yam_seed.png",
    "item_yam" : "bot/assets/images/farm/items/crops/Yam.png",

    "crop_cranberry_stage_1" : "bot/assets/images/farm/crops/cranberry/Cranberry_1.png",
    "crop_cranberry_stage_2" : "bot/assets/images/farm/crops/cranberry/Cranberry_2.png",
    "crop_cranberry_stage_3" : "bot/assets/images/farm/crops/cranberry/Cranberry_3.png",
    "crop_cranberry_stage_4" : "bot/assets/images/farm/crops/cranberry/Cranberry_4.png",
    "item_cranberry_seed" : "bot/assets/images/farm/items/seeds/Cranberry_seed.png",
    "item_cranberry" : "bot/assets/images/farm/items/crops/Cranberry.png",

    "crop_pumpkin_stage_1" : "bot/assets/images/farm/crops/pumpkin/Pumpkin_1.png",
    "crop_pumpkin_stage_2" : "bot/assets/images/farm/crops/pumpkin/Pumpkin_2.png",
    "crop_pumpkin_stage_3" : "bot/assets/images/farm/crops/pumpkin/Pumpkin_3.png",
    "crop_pumpkin_stage_4" : "bot/assets/images/farm/crops/pumpkin/Pumpkin_4.png",
    "item_pumpkin_seed" : "bot/assets/images/farm/items/seeds/Pumpkin_seed.png",
    "item_pumpkin" : "bot/assets/images/farm/items/crops/Pumpkin.png",

    "crop_artichoke_stage_1" : "bot/assets/images/farm/crops/artichoke/Artichoke_1.png",
    "crop_artichoke_stage_2" : "bot/assets/images/farm/crops/artichoke/Artichoke_2.png",
    "crop_artichoke_stage_3" : "bot/assets/images/farm/crops/artichoke/Artichoke_3.png",
    "crop_artichoke_stage_4" : "bot/assets/images/farm/crops/artichoke/Artichoke_4.png",
    "item_artichoke_seed" : "bot/assets/images/farm/items/seeds/Artichoke_seed.png",
    "item_artichoke" : "bot/assets/images/farm/items/crops/Artichoke.png",

    "crop_blueberry_stage_1" : "bot/assets/images/farm/crops/blueberry/Blueberry_1.png",
    "crop_blueberry_stage_2" : "bot/assets/images/farm/crops/blueberry/Blueberry_2.png",
    "crop_blueberry_stage_3" : "bot/assets/images/farm/crops/blueberry/Blueberry_3.png",
    "crop_blueberry_stage_4" : "bot/assets/images/farm/crops/blueberry/Blueberry_4.png",
    "item_blueberry_seed" : "bot/assets/images/farm/items/seeds/Blueberry_seed.png",
    "item_blueberry" : "bot/assets/images/farm/items/crops/Blueberry.png",

    "crop_strawberry_stage_1" : "bot/assets/images/farm/crops/strawberry/Strawberry_1.png",
    "crop_strawberry_stage_2" : "bot/assets/images/farm/crops/strawberry/Strawberry_2.png",
    "crop_strawberry_stage_3" : "bot/assets/images/farm/crops/strawberry/Strawberry_3.png",
    "crop_strawberry_stage_4" : "bot/assets/images/farm/crops/strawberry/Strawberry_4.png",
    "item_strawberry_seed" : "bot/assets/images/farm/items/seeds/Strawberry_seed.png",
    "item_strawberry" : "bot/assets/images/farm/items/crops/Strawberry.png",

    "crop_eggplant_stage_1" : "bot/assets/images/farm/crops/eggplant/Eggplant_1.png",
    "crop_eggplant_stage_2" : "bot/assets/images/farm/crops/eggplant/Eggplant_2.png",
    "crop_eggplant_stage_3" : "bot/assets/images/farm/crops/eggplant/Eggplant_3.png",
    "crop_eggplant_stage_4" : "bot/assets/images/farm/crops/eggplant/Eggplant_4.png",
    "item_eggplant_seed" : "bot/assets/images/farm/items/seeds/Eggplant_seed.png",
    "item_eggplant" : "bot/assets/images/farm/items/crops/Eggplant.png",

    "crop_grape_stage_1" : "bot/assets/images/farm/crops/grape/Grape_1.png",
    "crop_grape_stage_2" : "bot/assets/images/farm/crops/grape/Grape_2.png",
    "crop_grape_stage_3" : "bot/assets/images/farm/crops/grape/Grape_3.png",
    "crop_grape_stage_4" : "bot/assets/images/farm/crops/grape/Grape_4.png",
    "item_grape_seed" : "bot/assets/images/farm/items/seeds/Grape_seed.png",
    "item_grape" : "bot/assets/images/farm/items/crops/Grape.png",

    "crop_bok_choy_stage_1" : "bot/assets/images/farm/crops/bok_choy/Bok_Choy_1.png",
    "crop_bok_choy_stage_2" : "bot/assets/images/farm/crops/bok_choy/Bok_Choy_2.png",
    "crop_bok_choy_stage_3" : "bot/assets/images/farm/crops/bok_choy/Bok_Choy_3.png",
    "crop_bok_choy_stage_4" : "bot/assets/images/farm/crops/bok_choy/Bok_Choy_4.png",
    "item_bok_choy_seed" : "bot/assets/images/farm/items/seeds/Bok_Choy_seed.png",
    "item_bok_choy" : "bot/assets/images/farm/items/crops/Bok_Choy.png",

    "crop_sunflower_stage_1" : "bot/assets/images/farm/crops/sunflower/sunflower_1.png",
    "crop_sunflower_stage_2" : "bot/assets/images/farm/crops/sunflower/sunflower_2.png",
    "crop_sunflower_stage_3" : "bot/assets/images/farm/crops/sunflower/sunflower_3.png",
    "crop_sunflower_stage_4" : "bot/assets/images/farm/crops/sunflower/sunflower_4.png",
    "item_sunflower_seed" : "bot/assets/images/farm/items/seeds/sunflower_seed.png",
    "item_sunflower" : "bot/assets/images/farm/items/crops/sunflower.png",

    "chicken_1_image_key": "bot/assets/images/farm/animals/chicken/chicken_right.png",
    "chicken_2_image_key": "bot/assets/images/farm/animals/chicken/chicken_left.png",
    "cow_image_key" : "bot/assets/images/farm/animals/cow/cow_left.png",

    "item_chicken": "bot/assets/images/farm/animals/chicken/chicken_left.png",
    "item_cow": "bot/assets/images/farm/animals/cow/cow_left.png",

    "item_egg": "bot/assets/images/farm/items/animal_products/Egg.png",
    "item_milk": "bot/assets/images/farm/items/animal_products/Milk.png",

    "item_seaweed": "bot/assets/images/farm/seafood/Seaweed.png",
    "item_snail": "bot/assets/images/farm/seafood/Snail.png",
    "item_shrimp": "bot/assets/images/farm/seafood/Shrimp.png",
    "item_crab": "bot/assets/images/farm/seafood/Crab.png",
    "item_mussel": "bot/assets/images/farm/seafood/Mussel.png",
    "item_halibut": "bot/assets/images/farm/seafood/Halibut.png",
    "item_chub": "bot/assets/images/farm/seafood/Chub.png",
    "item_tilapia": "bot/assets/images/farm/seafood/Tilapia.png",
    "item_sturgeon": "bot/assets/images/farm/seafood/Sturgeon.png",
    "item_sea_cucumber": "bot/assets/images/farm/seafood/Sea_Cucumber.png",
    "item_squid": "bot/assets/images/farm/seafood/Squid.png",
    "item_red_snapper": "bot/assets/images/farm/seafood/Red_Snapper.png",
    "item_octopus": "bot/assets/images/farm/seafood/Octopus.png",
    "item_eel": "bot/assets/images/farm/seafood/Eel.png",
    "item_herring": "bot/assets/images/farm/seafood/Herring.png",
    "item_catfish": "bot/assets/images/farm/seafood/Catfish.png",
    "item_carp": "bot/assets/images/farm/seafood/Carp.png",
    "item_perch": "bot/assets/images/farm/seafood/Perch.png",
    "item_walleye": "bot/assets/images/farm/seafood/Walleye.png",
    "item_salmon": "bot/assets/images/farm/seafood/Salmon.png",
    "item_bream": "bot/assets/images/farm/seafood/Bream.png",
    "item_sardine": "bot/assets/images/farm/seafood/Sardine.png",
    "item_tuna": "bot/assets/images/farm/seafood/Tuna.png",
    "item_anchovy": "bot/assets/images/farm/seafood/Anchovy.png",
    "item_lobster": "bot/assets/images/farm/seafood/Lobster.png",
    "item_pufferfish": "bot/assets/images/farm/seafood/Pufferfish.png",

    "item_cheese": "bot/assets/images/farm/food/Cheese.png",
    "item_wheat_flour": "bot/assets/images/farm/food/Wheat_Flour.png",
    "item_oil": "bot/assets/images/farm/food/Oil.png",
    "item_sugar": "bot/assets/images/farm/food/Sugar.png",
    "item_fried_egg": "bot/assets/images/farm/food/Fried_Egg.png",
    "item_omelet": "bot/assets/images/farm/food/Omelet.png",
    "item_salad": "bot/assets/images/farm/food/Salad.png",
    "item_cheese_cauliflower": "bot/assets/images/farm/food/Cheese_Cauliflower.png",
    "item_parsnip_soup": "bot/assets/images/farm/food/Parsnip_Soup.png",
    "item_fried_calamari": "bot/assets/images/farm/food/Fried_Calamari.png",
    "item_pizza": "bot/assets/images/farm/food/Pizza.png",
    "item_bean_hotpot": "bot/assets/images/farm/food/Bean_Hotpot.png",
    "item_carp_surprise": "bot/assets/images/farm/food/Carp_Surprise.png",
    "item_hashbrowns": "bot/assets/images/farm/food/Hashbrowns.png",
    "item_pancakes": "bot/assets/images/farm/food/Pancakes.png",
    "item_salmon_dinner": "bot/assets/images/farm/food/Salmon_Dinner.png",
    "item_bread": "bot/assets/images/farm/food/Bread.png",
    "item_pink_cake": "bot/assets/images/farm/food/Pink_Cake.png",
    "item_rhubarb_pie": "bot/assets/images/farm/food/Rhubarb_Pie.png",
    "item_cookie": "bot/assets/images/farm/food/Cookie.png",
    "item_spaghetti": "bot/assets/images/farm/food/Spaghetti.png",
    "item_fried_eel": "bot/assets/images/farm/food/Fried_Eel.png",
    "item_sashimi": "bot/assets/images/farm/food/Sashimi.png",
    "item_maki_roll": "bot/assets/images/farm/food/Maki_Roll.png",
    "item_ice_cream": "bot/assets/images/farm/food/Ice_Cream.png",
    "item_crab_cakes": "bot/assets/images/farm/food/Crab_Cakes.png",
    "item_beer": "bot/assets/images/farm/food/Beer.png",
    "item_tortilla": "bot/assets/images/farm/food/Tortilla.png",
    "item_vinegar": "bot/assets/images/farm/food/Vinegar.png",
    "item_mayonnaise": "bot/assets/images/farm/food/Mayonnaise.png",
    "item_baked_fish": "bot/assets/images/farm/food/Baked_Fish.png",
    "item_strawberry_lover_pie": "bot/assets/images/farm/food/Strawberry_Lover_Pie.png",
    "item_fish_taco": "bot/assets/images/farm/food/Fish_Taco.png",
    "item_escargot": "bot/assets/images/farm/food/Escargot.png",
    "item_lobster_bisque": "bot/assets/images/farm/food/Lobster_Bisque.png",
    "item_cranberry_candy": "bot/assets/images/farm/food/Cranberry_Candy.png",
    "item_blackberry_cobbler": "bot/assets/images/farm/food/Blackberry_Cobbler.png",
    "item_fruit_salad": "bot/assets/images/farm/food/Fruit_Salad.png",
    "item_pumpkin_pie": "bot/assets/images/farm/food/Pumpkin_Pie.png",
    "item_artichoke_dip": "bot/assets/images/farm/food/Artichoke_Dip.png",
    "item_cranberry_sauce": "bot/assets/images/farm/food/Cranberry_Sauce.png",
    "item_fish_burger": "bot/assets/images/farm/food/fish_Burger.png",
    "item_stuffing": "bot/assets/images/farm/food/Stuffing.png",
    "item_super_meal": "bot/assets/images/farm/food/Super_Meal.png",
    "item_pumpkin_soup": "bot/assets/images/farm/food/Pumpkin_Soup.png",
    "item_autumn_bounty": "bot/assets/images/farm/food/Autumn_Bounty.png",
    "item_blueberry_tart": "bot/assets/images/farm/food/Blueberry_Tart.png",
    "item_spicy_octopus": "bot/assets/images/farm/food/Spicy_octopus.png",
    "item_tom_yum_soup": "bot/assets/images/farm/food/Tom_yum_Soup.png",
    "item_pepper_poppers": "bot/assets/images/farm/food/Pepper_Poppers.png",
    "item_treat": "bot/assets/images/farm/food/Treat.png",

    "item_sickle" : "bot/assets/images/farm/tools/sickle.png",
    "item_bamboo_rod" : "bot/assets/images/farm/tools/Bamboo_rod.png",
    "item_iron_rod" : "bot/assets/images/farm/tools/steel_Rod.png",
    "item_legendary_rod" : "bot/assets/images/farm/tools/legendary_Rod.png",
    "item_copper_watering_can" : "bot/assets/images/farm/tools/Copper_Watering_Can.png",
    "item_steel_watering_can" : "bot/assets/images/farm/tools/Steel_Watering_Can.png",
    "item_gold_watering_can" : "bot/assets/images/farm/tools/Gold_Watering_Can.png",
    "item_legendary_watering_can" : "bot/assets/images/farm/tools/legendary_Watering_Can.png",
    "item_milk_pail" : "bot/assets/images/farm/tools/Milk_Pail.png",

    "currency_chill_coin": "bot/assets/images/common/cs_coin.png",
    "level": "bot/assets/images/common/level.png",
    "exp": "bot/assets/images/common/xp.png",
    "clock": "bot/assets/images/common/clock.png",
    "shopScreen" : "bot/assets/images/farm/ui/shop.png",
    "recipesScreen": "bot/assets/images/farm/ui/recipes_table.png",
    "fishingRankingsScreen": "bot/assets/images/farm/ui/fishing_rankings.png",
    "trainRankingsScreen": "bot/assets/images/farm/ui/train_ranking.png",
    "chatRankingsScreen": "bot/assets/images/ui/chat_ranking.png",
    "staffChatRankingsScreen": "bot/assets/images/ui/staff_chat_ranking.png",
    "voiceRankingsScreen": "bot/assets/images/ui/voice_ranking.png",
    "train" : "bot/assets/images/farm/buildings/train.png",
    "item_bug": "bot/assets/images/farm/animals/bug.png",
    "memberInfo": "bot/assets/images/ui/memberInfo.png",
    "serverInfo": "bot/assets/images/ui/serverInfo.png",
    "dailyTask": "bot/assets/images/farm/ui/dailytask.png",
}

ASSET_IMAGE_URLS = {
    "sakura": "https://cdn.discordapp.com/attachments/1357327625051443291/1521040655864827995/builed_farm.png?ex=6a4362ff&is=6a42117f&hm=ad0428d37763eb7a2a816309270bef159f6585af4bd386cf7c89f564924c91a5&",
    "snow": "https://cdn.discordapp.com/attachments/1357327625051443291/1521040778145697832/builed_farm.png?ex=6a43631d&is=6a42119d&hm=15703d6ee576cf9a2c70d3ef9c367776ae6be02b6fd72fa4113e45038600acdb&",
    "christmas": "https://cdn.discordapp.com/attachments/1357327625051443291/1521040202422812803/builed_farm.png?ex=6a436293&is=6a421113&hm=20df58ce957240ff63a67cbeaa8aac16980d631bdf86adf86eddf1efd2b2c2ca&",
    "halloween": "https://cdn.discordapp.com/attachments/1357327625051443291/1521040500650414141/builed_farm.png?ex=6a4362da&is=6a42115a&hm=340b3c7a040a28e7b5bbc7105cb37f8fad6bcc9cd05869c6de91d74a95f28402&",
    "newYear": "https://cdn.discordapp.com/attachments/1357327625051443291/1521040891815661639/builed_farm.png?ex=6a436338&is=6a4211b8&hm=a17601f2baa70b07038847f9d7d9a0cdfd4f3a0cb4735879cdb3918304dfd2a0&",
    "cyberpunk": "https://cdn.discordapp.com/attachments/1357327625051443291/1521040362888757248/builed_farm.png?ex=6a4362ba&is=6a42113a&hm=0d5e0b90dcbb147014d84ed0a78cd3070de6ed4c02a58fa2f41618d1ecbf7908&",
}